[functions]
directory = "netlify/functions" 

[build]
  command = ""
  functions = "netlify/functions"   # where our function lives
  publish = "public"                 # optional; static files if any


[[headers]]
  for = "/*.html"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"

[[headers]]
  for = "/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"

[[headers]]
  for = "/embed.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
